// Svelte/src/components/MemoryCard.svelte
<script>
  import { createEventDispatcher } from 'svelte'
  import backSVG from '../assets/js-badge.svg'

  // PROPS
  export let framework
  export let card

  const dispatch = createEventDispatcher();

  // HANDLERS
  function flip(e) {
    dispatch('flip', {
      card: e.currentTarget
    });
  }
</script>

<div
  data-framework={framework}
  class={`memory-card`}
  on:click={flip}
>
  <img
    class={'back-face'}
    src={backSVG}
    alt="Click me!"
  />
  <img
    class='front-face'
    src={`/src/assets/${card.face}`}
    alt='card face'
  />
</div>

// TypeScript/TypeScript-React/src/components/MemoryCard.tsx
import { MemoryCardProps } from "../data/props";
import JavaScript from "../assets/js-badge.svg";

export const MemoryCard = (props: MemoryCardProps) => {
  return (
    <div className="memory-card">
      <img className="front-face" src={props.image} alt={props.name} />
      <img className="back-face" src={JavaScript} alt="JavaScript" />
    </div>
  );
}
