// Svelte/src/App.svelte
<script>
  import { onMount } from "svelte";
  import MemoryCard from "./components/MemoryCard.svelte";

  const cards = [
		{
			name: "react",
			face: "react.svg",
		},
		{
			name: "ember",
			face: "ember.svg",
		},
		{
			name: "vue",
			face: "vue.svg",
		},
		{
			name: "node",
			face: "node.svg",
		},
		{
			name: "svelte",
			face: "svelte.svg",
		},
		{
			name: "angular",
			face: "angular.svg",
		},
	]

	// STATE
	let lockBoard = false
	let firstCard = null
	let secondCard = null

	// HELPERS
	function unflipCards() {
		setTimeout(() => {
			firstCard.classList.remove('flip')
			secondCard.classList.remove('flip')
			resetBoard()
		}, 1500)
	}

	function disableCards() {
		firstCard.removeEventListener('click', firstCard)
		secondCard.removeEventListener('click', secondCard)
		resetBoard()
	}

	function resetBoard() {
		firstCard = secondCard = null
		lockBoard = false
	}

	// HANDLERS
	function handleCardFlip(e) {
		const card = e.detail.card

		if (lockBoard)	return

		if (card === firstCard) return

		card.classList.add('flip')

		if (!firstCard) {
			firstCard = card
			return
		}

		secondCard = card
		
		lockBoard = true
		if (firstCard.dataset['framework'] === secondCard.dataset['framework']) {
			disableCards()
		} else {
			unflipCards()
		}
	}
	
	// RUNS AFTER THE COMPONENT FIRST RENDER
	onMount(() => {
		// randomize the position of card
		const cards = document.querySelectorAll('.memory-card')

		cards.forEach((card) => {
			const randomPos = Math.floor(Math.random() * cards.length)
			// @ts-ignore
			card.style.order = randomPos
		})
	})
</script>

<main class="memory-game">
  {#each cards as card}
    <MemoryCard 
			on:flip={handleCardFlip}
			framework={`${card.name}`}
      card={card} 
			/>
			<MemoryCard 
			on:flip={handleCardFlip}
			framework={`${card.name}`}
      card={card} 
    />
  {/each}
</main>

// React/react-memory-game/src/App.js
import MemoryCard from "./components/MemoryCard";

function App() {
    const cards = document.querySelectorAll(".memory-card");

    let hasFlippedCard = false;
    let lockBoard = false;
    let firstCard, secondCard;

    function flipCard() {
        if (lockBoard) {
            return;
        }
        if (this === firstCard) {
            return;
        }
        this.classList.add("flip");

        if (!hasFlippedCard) {
            hasFlippedCard = true;
            firstCard = this;
            return;
        }
        secondCard = this;
        /* hasFlippedCard = false; */

        checkForMatch();
    }

    function checkForMatch() {
        let isMatch =
            firstCard.dataset.framework === secondCard.dataset.framework;
        isMatch ? disableCards() : unflipCards();
    }

    function disableCards() {
        firstCard.removeEventListener("click", flipCard);
        secondCard.removeEventListener("click", flipCard);
        resetBoard();
    }

    function unflipCards() {
        lockBoard = true;
        setTimeout(() => {
            firstCard.classList.remove("flip");
            secondCard.classList.remove("flip");
            resetBoard();
        }, 1500);
    }

    function resetBoard() {
        hasFlippedCard = lockBoard = false;
        firstCard = secondCard = false;
    }

    cards.forEach((card) => {
        const randomPos = Math.floor(Math.random() * cards.length);
        card.style.order = randomPos;
    });

    cards.forEach((card) => card.addEventListener("click", flipCard));

    return (
        <div className="App">
            {/* <!-- Game container --> */}
            <section className="memory-game">
                <MemoryCard
                    dataFramework=""
                    frontFace={require("./img/angular.svg").default}
                    alt="angular"
                />
                <MemoryCard
                    dataFramework=""
                    frontFace={require("./img/angular.svg").default}
                    alt="angular"
                />
                <MemoryCard
                    dataFramework="React"
                    frontFace={require("./img/react.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="React"
                    frontFace={require("./img/react.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="ember"
                    frontFace={require("./img/ember.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="ember"
                    frontFace={require("./img/ember.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="vue"
                    frontFace={require("./img/vue.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="vue"
                    frontFace={require("./img/vue.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="node"
                    frontFace={require("./img/node.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="node"
                    frontFace={require("./img/node.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="svelte"
                    frontFace={require("./img/svelte.svg").default}
                    alt=""
                />
                <MemoryCard
                    dataFramework="svelte"
                    frontFace={require("./img/svelte.svg").default}
                    alt=""
                />
            </section>
        </div>
    );
}

export default App;
